version: "2"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
plugins:
  eslint:
    enabled: false
exclude_patterns:
  - "docs/"
  - "tests/"
  - "**/node_modules/"
