language: python
python:
  - "3.8"
addons:
  chrome: stable
install:
  - pip install -r tests/requirements.txt
  - wget http://chromedriver.storage.googleapis.com/85.0.4183.38/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.8.0/bin/
script:
  - cd tests
  - python main.py