os: linux
language: python
python:
  - "3.7"
addons:
  chrome: stable
cache:
  - pip
  - yarn: true
  - directories:
    - node_modules
install:
  - pip install -r requirements.txt
services:
  - docker
before_script:
  - docker-compose up -d
script:
  - CYPRESS_BASE_URL=https://wazimap-staging.netlify.app npm run cypress
after_script:
  - docker-compose down
