os: linux
language: python
python:
  - "3.7"
addons:
  chrome: stable
cache:
  - pip
  - yarn: true
  - directories:
    - node_modules
install:
  - pip install -r requirements.txt
script:
  - ./runTest.sh
