os: linux
language: node_js
node_js:
  - "14"
addons:
  chrome: stable
cache:
  - yarn: true
  - directories:
    - node_modules
    - .cache/Cypress
install:
  - npm install
script:
  - CYPRESS_BASE_URL=https://wazimap-staging.netlify.app npm run cypress
