os: linux
language: python
python:
  - "3.7"
addons:
  chrome: stable
cache:
  - pip
  - yarn: true
  - directories:
    - node_modules
install:
  - pip install -r requirements.txt
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 10 # give xvfb some time to start
  - yarn start  # start a Web server
  - sleep 50 # give Web server some time to bind to sockets, etc
script:
  - ./run_test.sh
