language: python

python:
  - "3.8"

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
install:
  - pip install -r tests/requirements.txt

before_script:
  - google-chrome --version
  - ln -s /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"

script:
  - google-chrome --version
  - cd tests
  - python main.py